<?php
/**
 * _embed-fonts.php — write the `@font-face` block into the four static mockups.
 *
 * Run:  php skills/html-mockup/assets/fonts/_embed-fonts.php
 *       php skills/html-mockup/assets/fonts/_embed-fonts.php --check   (writes nothing, exits 1 if stale)
 *
 * The gallery does NOT go through here: `../gallery/index.html` is generated, so it calls
 * `nm_font_faces()` from `_build-gallery.php` directly. These four are hand-maintained files, so
 * the block is written INTO them and marked, rather than regenerated around them.
 *
 * IDEMPOTENT ON PURPOSE. The managed region is delimited, so a second run replaces it instead of
 * stacking a second copy — and `--check` is what a reviewer runs to find out whether the committed
 * files still match the committed woff2. Without that, a font swap would leave four HTML files
 * carrying the old bytes and nothing would say so.
 *
 * LINE ENDINGS ARE PER-FILE AND ARE NOT ASSUMED. These four are CRLF while everything under
 * `../gallery/` is LF, in a tree with `core.autocrlf=true` and no `.gitattributes`. Writing "\n"
 * into a CRLF file turns a six-line insertion into a whole-file diff, so the ending is measured
 * from the file being edited. (Measure it by counting CR BYTES — `grep -c $'\r$'` reports CRLF for
 * LF files under Git Bash, which is how this was nearly got wrong.)
 */

require __DIR__ . '/_fonts.php';

$BEGIN = '  /* NM-FONTS:BEGIN — generated by assets/fonts/_embed-fonts.php · do not hand-edit */';
$END   = '  /* NM-FONTS:END */';

$check   = in_array( '--check', $argv, true );
$targets = array(
	'corporate-mockup.html',
	'ecommerce-mockup.html',
	'proof-direct-mockup.html',
	'proof-editorial-mockup.html',
);

$stale = array();
$total = 0;

foreach ( $targets as $name ) {
	$path = __DIR__ . '/../' . $name;
	if ( ! is_file( $path ) ) {
		fwrite( STDERR, "embed-fonts: FAIL — $name is not beside this directory\n" );
		exit( 1 );
	}
	$before = file_get_contents( $path );

	/* The file's OWN ending, measured, never assumed. */
	$crlf = ( substr_count( $before, "\r\n" ) > 0 );
	$eol  = $crlf ? "\r\n" : "\n";

	/* Strip any managed region first, so detection reads the DESIGN's font stacks and not the
	   `font-family` descriptors of a block this tool wrote on a previous run. */
	$naked = preg_replace(
		'/' . preg_quote( $BEGIN, '/' ) . '.*?' . preg_quote( $END, '/' ) . '\R?/s',
		'',
		str_replace( "\r\n", "\n", $before )
	);

	$families = nm_font_families_asked_for( $naked );
	if ( array() === $families ) {
		fwrite( STDERR, "embed-fonts: FAIL — $name names no font family; nothing to embed and nothing that would render\n" );
		exit( 1 );
	}

	/* Straight after `<style>`, which puts the faces ahead of every rule that uses them and, more
	   to the point, ahead of the first `:root{…}` block — the one RT_MOCKUP_NO_AXES reads. Nothing
	   emitted here contains the literal `:root{`, so that scan still lands on the real one. */
	if ( ! preg_match( '/<style>\n/', $naked ) ) {
		fwrite( STDERR, "embed-fonts: FAIL — $name has no `<style>` line to insert after\n" );
		exit( 1 );
	}
	$block = $BEGIN . "\n" . nm_font_faces( $families ) . "\n" . $END . "\n";
	$after = preg_replace( '/<style>\n/', "<style>\n" . $block, $naked, 1 );
	$after = str_replace( "\n", $eol, $after );

	$cost  = nm_font_bytes( $families );
	$delta = strlen( $after ) - strlen( $before );
	$total += $cost['b64'];

	if ( $after === $before ) {
		printf( "  %-28s up to date  (%s · %s KB base64)\n", $name, implode( ' + ', $families ), number_format( $cost['b64'] / 1024, 1 ) );
		continue;
	}
	if ( $check ) {
		$stale[] = $name;
		printf( "  %-28s STALE       (%+d bytes if written)\n", $name, $delta );
		continue;
	}
	file_put_contents( $path, $after );
	printf(
		"  %-28s written     (%s · %s KB base64 · %+d bytes · %s)\n",
		$name,
		implode( ' + ', $families ),
		number_format( $cost['b64'] / 1024, 1 ),
		$delta,
		$crlf ? 'CRLF' : 'LF'
	);
}

if ( $check && array() !== $stale ) {
	fwrite( STDERR, "embed-fonts: STALE — " . implode( ', ', $stale )
		. " do not match the committed woff2. Run this tool without --check.\n" );
	exit( 1 );
}
printf( "embed-fonts: %d file(s), %s KB base64 across them\n", count( $targets ), number_format( $total / 1024, 1 ) );
